# 制御周波数
hz: 10                   # ループ周波数 [Hz]

# frame_id
path_frame: "map"        # path

# 座標
# x: [0.0, 0.5, 1.0, 1.5]  # x座標 [m]
x: [0.0, 1.0, 2.0, 3.0]  # x座標 [m]
y: [2.7, 6.0, 5.0, 6.5]  # y座標 [m]